### PR TITLE
Release 1.2.1

### PR DESCRIPTION
**Pull request by lmakarov**
- Added Docker healthcheck support
- Minor fixes and cleanup in `ssh-key`
- Cleanup and fixes in build and CI

### CODE REVIEW

**Comment by achekulaev** [comment]
As in DNS I guess healthcheck interval could be lowered to make things faster.

**Comment by lmakarov** [comment]
I lowered retries instead. Container now has 15s (5x3) to start, which should be sufficient.

**Comment by achekulaev** [comment]
> I lowered retries instead. Container now has 15s (5x3) to start, which should be sufficient.

Lets look at the sequence of events. Container starts, healthcheck runs, it's not healthy yet, obviously, it needs time. 
Now healthcheck waits for 5 seconds and it is a blocking thing. fin will not let other containers to start until system ones started. So everything is blocked for 5 seconds while it could be 2.

**Comment by lmakarov** [comment]
> fin will not let other containers to start until system ones started

That has not yet been implemented. For now, healthchecks in the system services are informative only.

**Comment by achekulaev** [comment]
@lmakarov sure, sure, but _when_ it is implemented, fin _will_ be blocking future actions until system containers started, so why wait?

**Comment by lmakarov** [comment]
When we get there, we'll do thorough testing and adjust the values based on the results.
Neither of the values we set now may be the best fit. So, what's there now is good. What it should actually be - we'll figure out as we get there at some point.

**Pull request merged**
